config/routes.rb
RiskManagement::Application.routes.draw do
  root "static_pages#home"
  match '/about', 	 to: "static_pages#about",    via: 'get'
  match '/contact',  to: "static_pages#contact",  via: 'get'
  match '/help', 		 to: "static_pages#help",     via: 'get'
  match '/training', to: "static_pages#training", via: 'get'
  match '/services', to: "static_pages#services", via: 'get'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

	def help
	end
	
	def training
	end

	def services
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def full_title(page_title)
		base_title = "S&J Risk Management"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href= <%= root_path%>> S&J Risk Management</a>
		by Chris LaBarge
	</small>
	<nav>
		<ul>
			<li><%= link_to "About S&J", about_path %></li>
			<li><%= link_to "Contact Information", contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to 'S&J', root_path, id: "logo" %>

      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "About",      about_path %></li>
          <li><%= link_to "Services",   services_path %></li>
          <li><%= link_to "Training",   training_path %></li>
          <li><%= link_to "Contact",    contact_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
	

		<%= render 'layouts/shim'%>
  </head>
  <body>
		<%= render 'layouts/header' %>
   <% if current_page?('/')%> 
    <div id="myCarousel" class="carousel slide">

     
    <div class="carousel-inner">

        <div class="item active">
						<%= image_tag('background_2.jpg', class:'test')%>
            <div class="container welcome">
                <div class='row'>  
              		<div class='span4'>
              			   
              			  <%=image_tag('logo_big.gif', class: 'poop')%>
              		</div>
              		<div class='span4'>
              			<h1>Risk Management</h1>
						<a class="btn btn-large btn-success" href="#">Find Out More</a>

              		</div>
              		</div>
              <!--  <div class="carousel-caption">
               
                    <h1>HELLO</h1>
                    
                    <a class="btn btn-large btn-primary" href="#"></a>
                		
                </div> -->
            </div>
        </div>
        </div>
        </div>
       	<div class="center container marketing ">
       	<%= yield %>
       	</div>
       <% else%>
    <div class="container">
      <%= yield %>
    	<%= render 'layouts/footer'%>
    </div>
  	<%end%>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About')%>


<div class="hero-unit" >
<%=image_tag("me_pointing_text.jpg", alt: "About")%>
</div>
<div class="center hero-unit" >
<h3>Welcome to S & J Risk Management. We have over 
36 years of safety and risk management experience with 
proven results. Whether your needs require on-site safety 
expertise, training or a comprehensive risk management program,
we are here to serve you. Risk Management is an essential 
part of your business. In order to successfully compete,
it is critical to plan and integrate loss prevention and
control into your work and field operations.</h3>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact')%>

<div class="center hero-unit">
	
	<h1>Contact Us Today!!</h1>
	<p>This will be all the contact info my nigga guy</p>
	</div>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help')%>

<h1>Help</h1>
<p>Do you need help?</p>

app/views/static_pages/home.html.erb
       <div class="row">
        <div class="span4">
                <%=image_tag("point.jpg", class: 'img-circle', width:'200', height: '300')%> 

              <h1>Services</h1>
        			<p>wrg adfl ;gka;  dfls asdasdas gkswqeljwekjwe'</p>
      				<a class="btn btn-large btn-primary" href="#">Learn More</a>
				</div>
				
				 <div class="span4">
                   <%=image_tag("training.jpg", class: 'img-circle', width:'200', height: '200')%> 

              <h1>Training</h1>
        			<p>wrgt;ladjfgl; jkfsglkdfslg kadfl; gkadfl;gka; dflsgks'</p>
      				<a class="btn btn-large btn-primary" href="#">Learn More</a>
				</div>
				
				 <div class="span4">
              <%=image_tag("coney_1.jpg", class: 'img-circle', width:'200', height: '140')%> 
              <h1>Contact</h1>
        			<p>wrgt;lad jfgl;jkfs glkdfslgkadfl;gka dfl;gka;dflsgks'</p>
      				<a class="btn btn-large btn-primary" href="#">Learn More</a>
				</div>
				
				</div>
<!--

  <%=image_tag("logo_big.gif", class: 'img-circle', width: '100',  height: '100')%> 

<div id="myCarousel" class="carousel slide">

    <div class="carousel-inner">
        <div class="item active">
						<%= image_tag('background_2.jpg')%>
            <div class="container">
                <div class="carousel-caption">
                    <h1></h1>
                    <p class="lead"></p>
                    <a class="btn btn-large btn-primary" href="#"></a>
                </div>
            </div>
        </div>
        </div> -->
         
	
	
<!--	<div class="hero-unit"  >
	
	<h1> HI</h1>
	<h1></h1>
  
  	<%=image_tag("logo_big.gif", class: "pull-left")%>
		
			<div id="row">
			  <h1>Risk Management</h1>
			  <h2>Welcome to the S&J Risk Management websiteblahhhhhhh blah blahhhhhhhhhhh blah bahsdjd blahjkjk</h2>

				<%= link_to "Learn More", about_path, class: "btn btn-large btn-primary" %>
			</div>
		
	</div> --> 

<!--	<div class="center hero-unit">
		<h2>Welcome to the S&J Risk Management websiteblahhhhhhh blah blahhhhhhhhhhh blah bahsdjd blahjkjk</h2>

	<%= link_to "Learn More", '#', class: "btn btn-large btn-primary" %>
	</div> 
	
		
		<div class="hi_logo">
			<%=image_tag("logo_big.gif", alt: "logo")%>
		</div>
			<div class="hi_text">
		
			<h1>S&J Risk Management</h1>
		<div>
	
	
	-->


<!--<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %> 
		FOR RUBY ON RAILS LOGO, WE DON'T NEED IT, BUT IT EXPLAINS IN 5.1.1 
		HOW TO USE IT AND WHERE TO PUT THE IMAGES-->

app/views/static_pages/services.html.erb
<% provide(:title, 'Services') %>

<div class="center hero-unit">
<h1> Our Services </h1>
<ul>
	<li>Hey</lu>
</ul>
</div>

app/views/static_pages/training.html.erb
<% provide(:title, 'Training')%>

<div class="center hero-unit">
<h1>S&J Risk Management Training</h1>
<p>Here at S&J we provide yadda yadda yadda</p>
</div>